# Generated by Django 5.1.7 on 2025-03-11 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('active_user', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('exit_date', models.DateTimeField(auto_now=True)),
                ('session_duration', models.DurationField(blank=True, null=True)),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Finalizado', 'Finalizado')], max_length=50)),
                ('employees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employees')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_progress', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Finalizado', 'Finalizado')], max_length=50)),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employees')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.items')),
            ],
        ),
        migrations.CreateModel(
            name='AdvanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.DecimalField(decimal_places=2, max_digits=5)),
                ('state', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Finalizado', 'Finalizado')], max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('employees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employees')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.items')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Finalizado', 'Finalizado')], max_length=50)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.items')),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ot_number', models.CharField(max_length=20, unique=True)),
                ('empresa', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Finalizado', 'Finalizado')], max_length=50)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('employees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employees')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='workorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workorder'),
        ),
        migrations.CreateModel(
            name='AdvanceOt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.DecimalField(decimal_places=2, max_digits=5)),
                ('state', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Finalizado', 'Finalizado')], max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workorder')),
            ],
        ),
    ]
