# Generated by Django 5.1.7 on 2025-03-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='items',
            constraint=models.UniqueConstraint(fields=('item_number', 'workorder'), name='unique_item_per_ot'),
        ),
    ]
