# Generated by Django 5.1.7 on 2025-03-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_items_item_number_alter_tasks_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceitem',
            name='state',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='advanceot',
            name='state',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeprogress',
            name='state',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='state',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='itemtasks',
            name='state',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='state',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=50),
        ),
    ]
